"use client";

import { useEffect, useState } from "react";
import type { HospitalField } from "@/shared/types/hospital.types";
import { api } from "@/shared/lib/http/api";
import Autocomplete, { type AutocompleteOption } from "@/components/ui/autocomplete";
import RichTextEditor from "@/components/forms/RichTextEditor";
import { formatValue, normalizeRows, relationLabel } from "./utils";
import { ModulePermissionsEditor } from "./ModulePermissionsEditor";

export function FieldInput({ field, value, onChange, locale = "fr", form }: { field: HospitalField; value: any; onChange: (value: any) => void; locale?: string; form?: Record<string, any> }) {
  const base = "w-full border border-slate-200 bg-slate-50 px-3 py-3 text-sm font-semibold outline-none focus:border-blue-700 focus:bg-white";
  const autoBase = "w-full border border-dashed border-slate-200 bg-slate-100 px-3 py-3 text-sm font-black text-slate-500 outline-none";
  const [options, setOptions] = useState<AutocompleteOption[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!field.reference) return;
    let mounted = true;
    setLoading(true);
    api.get(field.reference.endpoint)
      .then((response) => {
        if (!mounted) return;
        setOptions(normalizeRows(response.data).map((row) => ({
          id: String(row[field.reference?.valueKey ?? "id"] ?? row.id ?? ""),
          label: relationLabel(row, field.reference?.labelKeys ?? []),
          description: relationLabel(row, field.reference?.descriptionKeys ?? []),
        })).filter((option) => option.id));
      })
      .catch(() => mounted && setOptions([]))
      .finally(() => mounted && setLoading(false));
    return () => { mounted = false; };
  }, [field.reference?.endpoint]);

  const datalistId = `list-${field.name}`;
  const selectedValues = Array.isArray(value) ? value : typeof value === "string" && value ? [value] : [];

  return (
    <label className={field.type === "multiselect" || field.type === "module-permissions" || field.type === "price-list-items" ? "block md:col-span-2" : "block"}>
      <span className="mb-2 block text-xs font-black uppercase tracking-wide text-slate-500">{field.label}{field.required ? " *" : ""}</span>
      {field.type === "module-permissions" ? (
        <ModulePermissionsEditor value={value} roles={form?.roles} onChange={onChange} locale={locale} />
      ) : field.autoGenerated ? (
        <input value={value ? formatValue(value) : locale === "en" ? "Generated automatically" : "Généré automatiquement"} readOnly className={autoBase} />
      ) : field.type === "price-list-items" ? (
        <PriceListItemsField value={value} onChange={onChange} locale={locale} />
      ) : field.reference ? (
        <Autocomplete value={String(value ?? "")} options={options} isLoading={loading} placeholder={field.placeholder || `${locale === "en" ? "Select" : "Sélectionner"} ${field.label.toLowerCase()}`} searchPlaceholder={`${locale === "en" ? "Search" : "Rechercher"} ${field.label.toLowerCase()}`} emptyText={locale === "en" ? "No result" : "Aucun résultat"} onSelect={(option) => onChange(option.id)} showIdFallback={false} />
      ) : field.type === "multiselect" ? (
        <div className="grid gap-2 border border-slate-200 bg-slate-50 p-3 md:grid-cols-2">
          {(field.options ?? []).map((option) => {
            const checked = selectedValues.includes(option.value);
            return (
              <label key={option.value} className={`flex items-center gap-2 border bg-white px-3 py-2 text-xs font-black ${checked ? "border-blue-700 text-blue-800" : "border-slate-200 text-slate-700"}`}>
                <input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked ? [...selectedValues, option.value] : selectedValues.filter((item) => item !== option.value))} />
                {option.label}
              </label>
            );
          })}
        </div>
      ) : field.type === "select" && field.allowCustom ? (
        <>
          <input list={datalistId} value={String(value ?? "")} onChange={(event) => onChange(event.target.value)} placeholder={locale === "en" ? "Select or create..." : "Sélectionner ou créer..."} className={base} />
          <datalist id={datalistId}>{(field.options ?? []).map((option) => <option key={option.value} value={option.value} />)}</datalist>
        </>
      ) : field.type === "select" ? (
        <select value={String(value ?? "")} onChange={(event) => onChange(event.target.value)} className={base}>
          <option value="">-</option>
          {(field.options ?? []).map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}
        </select>
      ) : field.type === "json" ? (
        <RichTextEditor value={jsonValueToEditor(value)} onChange={onChange} minHeight="min-h-32" />
      ) : field.type === "textarea" ? (
        <textarea value={typeof value === "string" ? value : JSON.stringify(value ?? {}, null, 2)} onChange={(event) => onChange(event.target.value)} placeholder={field.placeholder} className={`${base} h-28 text-sm`} />
      ) : field.type === "checkbox" ? (
        <input type="checkbox" checked={Boolean(value)} onChange={(event) => onChange(event.target.checked)} />
      ) : (
        <input type={field.type === "number" ? "number" : field.type === "date" ? "date" : field.type === "datetime" ? "datetime-local" : field.name === "password" || field.name.toLowerCase().includes("pin") ? "password" : "text"} value={value ?? ""} onChange={(event) => onChange(field.type === "number" ? Number(event.target.value) : event.target.value)} placeholder={field.name === "password" ? (locale === "en" ? "Minimum 10 characters" : "Minimum 10 caractères") : field.name.toLowerCase().includes("pin") ? "4 à 8 chiffres" : field.placeholder} className={base} />
      )}
    </label>
  );
}

function PriceListItemsField({ value, onChange, locale }: { value: any; onChange: (value: any) => void; locale: string }) {
  const rows = Array.isArray(value) ? value : [];
  const [services, setServices] = useState<Array<{ id: string; label: string; description: string }>>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    let mounted = true;
    setLoading(true);
    api.get("/pricing/services")
      .then((response) => mounted && setServices(normalizeRows(response.data).map((service) => ({
        id: String(service.id ?? ""),
        label: [service.name, service.code].filter(Boolean).join(" · "),
        description: [service.category, service.unit, service.sourceModule, service.sourceEvent].filter(Boolean).join(" · "),
      })).filter((service) => service.id)))
      .catch(() => mounted && setServices([]))
      .finally(() => mounted && setLoading(false));
    return () => { mounted = false; };
  }, []);

  const updateRow = (index: number, patch: Record<string, any>) => onChange(rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row));
  const addRow = () => onChange([...rows, { serviceId: "", unitPrice: "", insurancePrice: "" }]);
  const removeRow = (index: number) => onChange(rows.filter((_, rowIndex) => rowIndex !== index));

  return (
    <div>
      <div className="overflow-hidden border border-slate-200 bg-white">
        <div className="grid grid-cols-[minmax(220px,1.5fr)_140px_150px_44px] gap-2 bg-slate-50 px-3 py-2 text-[11px] font-black uppercase tracking-wide text-slate-500">
          <span>Prestation facturée</span><span>Prix patient</span><span>Prix assurance</span><span />
        </div>
        <div className="divide-y divide-slate-100">
          {rows.map((row, index) => (
            <div key={index} className="grid grid-cols-[minmax(220px,1.5fr)_140px_150px_44px] gap-2 p-3">
              <select value={row.serviceId ?? ""} onChange={(event) => updateRow(index, { serviceId: event.target.value })} className="border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-semibold outline-none focus:border-blue-700 focus:bg-white">
                <option value="">{loading ? "Chargement..." : "Choisir la prestation"}</option>
                {services.map((service) => <option key={service.id} value={service.id}>{service.label}{service.description ? ` (${service.description})` : ""}</option>)}
              </select>
              <input type="number" min="0" step="0.01" value={row.unitPrice ?? ""} onChange={(event) => updateRow(index, { unitPrice: event.target.value })} placeholder="0" className="border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-semibold outline-none focus:border-blue-700 focus:bg-white" />
              <input type="number" min="0" step="0.01" value={row.insurancePrice ?? ""} onChange={(event) => updateRow(index, { insurancePrice: event.target.value })} placeholder="Optionnel" className="border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-semibold outline-none focus:border-blue-700 focus:bg-white" />
              <button type="button" onClick={() => removeRow(index)} className="border border-slate-200 text-sm font-black text-slate-500 hover:bg-rose-50 hover:text-rose-700">×</button>
            </div>
          ))}
          {!rows.length ? <p className="p-4 text-sm font-semibold text-slate-500">{locale === "en" ? "Add services and their prices." : "Ajoutez les prestations et leurs montants."}</p> : null}
        </div>
      </div>
      <button type="button" onClick={addRow} className="mt-3 border border-blue-700 bg-white px-4 py-2 text-sm font-black text-blue-800 hover:bg-blue-50">Ajouter une prestation</button>
    </div>
  );
}

function jsonValueToEditor(value: any) {
  if (!value) return "";
  if (typeof value === "string") return value;
  if (typeof value === "object" && typeof value.content === "string") return value.content;
  return `<pre>${escapeHtml(JSON.stringify(value, null, 2))}</pre>`;
}

function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char] ?? char));
}
