import type { HospitalField } from "@/shared/types/hospital.types";
import type { OperationKind } from "./types";

export function cleanObject(input: Record<string, any>) {
  return Object.fromEntries(Object.entries(input).filter(([, value]) => value !== "" && value !== undefined && value !== null && value !== "{}" && value !== "[]"));
}

export function invoiceApiPayload(input: Record<string, any>) {
  const { collectNow, paymentMethod, paymentAmount, paymentReference, preview, ...payload } = input;
  return cleanObject(payload);
}

export function normalizeRows(data: any): any[] {
  if (Array.isArray(data)) return data;
  if (Array.isArray(data?.data)) return data.data;
  if (Array.isArray(data?.items)) return data.items;
  return data && typeof data === "object" ? [data] : [];
}

export function defaultForm(fields: HospitalField[], row?: Record<string, any>) {
  return Object.fromEntries(fields.map((field) => [field.name, row?.[field.name] ?? defaultFieldValue(field)]));
}

function defaultFieldValue(field: HospitalField) {
  if (field.type === "module-permissions" || field.type === "price-list-items" || field.type === "purchase-order-items" || field.type === "dispensation-items" || field.type === "prescription-items") return [];
  if (field.type === "json") return "";
  if (field.type === "number") return 0;
  if (field.type === "checkbox") return false;
  if (field.type === "multiselect") return [];
  if (field.name === "active") return "true";
  if (field.name === "currency") return "RWF";
  return "";
}

export function parseJsonPayload(value: string) {
  try {
    return JSON.parse(value || "{}");
  } catch {
    throw new Error("Le JSON avancé est invalide. Corrigez la syntaxe avant d’enregistrer.");
  }
}

export function cleanPayload(form: Record<string, any>, fields: HospitalField[]) {
  const out: Record<string, any> = {};
  for (const field of fields) {
    const value = form[field.name];
    if (field.autoGenerated && (value === "" || value === undefined || value === null)) continue;
    if (field.required && (value === "" || value === undefined || value === null || value === "{}" || value === "[]")) throw new Error(`${field.label} est obligatoire`);
    if (field.required && field.type === "multiselect" && (!Array.isArray(value) || value.length === 0)) throw new Error(`${field.label} est obligatoire`);
    if (value === "" || value === undefined || value === null) continue;
    if (field.type === "multiselect") {
      out[field.name] = Array.isArray(value) ? value : String(value).split(",").map((item) => item.trim()).filter(Boolean);
      continue;
    }
    if (field.type === "module-permissions") {
      out[field.name] = Array.isArray(value) ? value : [];
      continue;
    }
    if (field.type === "price-list-items") {
      const items = Array.isArray(value) ? value.filter((item) => item?.serviceId && Number.isFinite(Number(item?.unitPrice)) && Number(item.unitPrice) >= 0).map((item) => ({ serviceId: item.serviceId, unitPrice: Number(item.unitPrice), ...(item.insurancePrice === "" || item.insurancePrice === undefined || item.insurancePrice === null ? {} : { insurancePrice: Number(item.insurancePrice) }) })) : [];
      if (field.required && !items.length) throw new Error("Ajoutez au moins une prestation avec son montant.");
      out[field.name] = items;
      continue;
    }
    if (field.type === "purchase-order-items") {
      const items = Array.isArray(value) ? value.filter((item) => String(item?.description ?? "").trim() && Number.isFinite(Number(item?.quantity)) && Number(item.quantity) > 0 && Number.isFinite(Number(item?.unitPrice)) && Number(item.unitPrice) >= 0).map((item) => ({ description: String(item.description).trim(), quantity: Number(item.quantity), unitPrice: Number(item.unitPrice) })) : [];
      if (field.required && !items.length) throw new Error("Ajoutez au moins un article avec quantité et prix unitaire.");
      out[field.name] = items;
      continue;
    }
    if (field.type === "dispensation-items") {
      const items = Array.isArray(value) ? value.filter((item) => item?.medicineId && item?.batchId && Number.isFinite(Number(item?.quantity)) && Number(item.quantity) > 0).map((item) => ({ medicineId: item.medicineId, batchId: item.batchId, quantity: Number(item.quantity) })) : [];
      if (field.required && !items.length) throw new Error("Ajoutez au moins un médicament avec son lot et la quantité délivrée.");
      out[field.name] = items;
      continue;
    }
    if (field.type === "prescription-items") {
      const items = Array.isArray(value) ? value
        .filter((item) => String(item?.medicine ?? "").trim() && String(item?.dosage ?? "").trim() && String(item?.frequency ?? "").trim() && String(item?.duration ?? "").trim())
        .map((item) => ({
          ...(item.medicineId ? { medicineId: item.medicineId } : {}),
          medicine: String(item.medicine).trim(),
          dosage: String(item.dosage).trim(),
          frequency: String(item.frequency).trim(),
          duration: String(item.duration).trim(),
          ...(String(item.instructions ?? "").trim() ? { instructions: String(item.instructions).trim() } : {}),
        })) : [];
      if (field.required && !items.length) throw new Error("Ajoutez au moins un médicament avec dose, fréquence et durée.");
      out[field.name] = items;
      continue;
    }
    if (field.name === "password" && String(value).length < 10) throw new Error("Le mot de passe doit contenir au moins 10 caractères.");
    if (field.type === "number") {
      const numeric = Number(value);
      if (!Number.isFinite(numeric)) throw new Error(`${field.label} doit être un nombre valide`);
      out[field.name] = numeric;
      continue;
    }
    if (field.type === "json" && typeof value === "string") {
      try {
        out[field.name] = JSON.parse(value || "{}");
      } catch {
        out[field.name] = { content: value, format: "html" };
      }
      if (field.required && ((Array.isArray(out[field.name]) && out[field.name].length === 0) || (!Array.isArray(out[field.name]) && typeof out[field.name] === "object" && Object.keys(out[field.name] ?? {}).length === 0))) throw new Error(`${field.label} est obligatoire`);
      continue;
    }
    out[field.name] = value === "true" ? true : value === "false" ? false : value;
  }
  return out;
}

export function formatValue(value: any): string {
  if (value === null || value === undefined || value === "") return "-";
  if (isUuid(value)) return "Référence interne";
  if (Array.isArray(value)) {
    if (value.length && value.every(isUuid)) return `${value.length} référence${value.length > 1 ? "s" : ""} interne${value.length > 1 ? "s" : ""}`;
    return value.map(formatValue).filter((item) => item !== "-").join(", ");
  }
  if (value instanceof Date) return formatDateTime(value);
  if (typeof value === "string" && isIsoDateString(value)) return formatDateTime(new Date(value));
  if (typeof value === "object") {
    if (typeof value.content === "string") return cleanHtmlText(value.content);
    const readable = [
      value.label, value.name, value.title, value.code, value.invoiceNumber, value.medicalRecordNumber,
      value.patientName, value.practitionerName, value.prescriberName, value.employeeNumber,
      value.batchNumber, value.bagNumber, value.sku, value.status,
    ].map(formatValue).filter((item) => item !== "-" && item !== "Référence interne");
    if (readable.length) return readable.join(" · ");
    return Object.entries(value)
      .filter(([key, item]) => !isTechnicalKey(key) && item !== null && item !== undefined && item !== "")
      .map(([key, item]) => `${humanizeKey(key)}: ${formatValue(item)}`)
      .join(" · ") || "-";
  }
  return String(value);
}

export function isTechnicalKey(key: string) {
  return key === "id"
    || key === "organizationId"
    || key === "organization_id"
    || key === "deletedAt"
    || key === "deleted_at"
    || key === "passwordHash"
    || key === "password_hash"
    || key === "refreshTokenHash"
    || key === "refresh_token_hash"
    || key.endsWith("Id")
    || key.endsWith("Ids")
    || key.endsWith("_id")
    || key.endsWith("_ids");
}

function humanizeKey(key: string) {
  return key.replace(/_/g, " ").replace(/([A-Z])/g, " $1").replace(/^./, (value) => value.toUpperCase());
}

function cleanHtmlText(value: string) {
  return value
    .replace(/<\s*br\s*\/?>/gi, "\n")
    .replace(/<\s*\/div\s*>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#039;/g, "'")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .join("\n") || "-";
}

function isIsoDateString(value: string) {
  return /^\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}(?::\d{2}(?:\.\d{1,3})?)?(?:Z|[+-]\d{2}:?\d{2})?)?$/.test(value) && !Number.isNaN(new Date(value).getTime());
}

function formatDateTime(date: Date) {
  if (Number.isNaN(date.getTime())) return "-";
  const hasTime = date.getUTCHours() + date.getUTCMinutes() + date.getUTCSeconds() + date.getUTCMilliseconds() > 0;
  return new Intl.DateTimeFormat("fr-FR", hasTime ? { dateStyle: "medium", timeStyle: "short" } : { dateStyle: "medium" }).format(date);
}

export function readError(err: any) {
  const msg = err?.response?.data?.message ?? err?.response?.data?.detail ?? err?.message;
  const message = Array.isArray(msg) ? msg.join(", ") : String(msg || "Erreur inconnue");
  const status = err?.response?.status;
  const method = err?.config?.method ? String(err.config.method).toUpperCase() : "";
  const url = err?.config?.url ? String(err.config.url) : "";
  const context = [status ? `HTTP ${status}` : "", method, url].filter(Boolean).join(" · ");
  return context ? `${context} — ${message}` : message;
}

export function relationLabel(row: Record<string, any>, keys: string[]) {
  const fromConfig = keys.map((key) => row[key]).filter(isReadableReferencePart).map(formatValue);
  if (fromConfig.length) return fromConfig.join(" · ");
  const fallbackKeys = [
    "patientName", "practitionerName", "attendingPractitionerName", "prescriberName",
    "invoiceNumber", "medicalRecordNumber", "employeeNumber", "badgeNumber", "code", "sku",
    "batchNumber", "donorNumber", "bagNumber", "name", "title", "label", "chiefComplaint",
    "procedure", "testName", "ward", "room", "status", "createdAt",
  ];
  const fallback = fallbackKeys.map((key) => row[key]).filter(isReadableReferencePart).map(formatValue);
  return fallback.length ? fallback.join(" · ") : "Référence sans nom";
}

export function isUuid(value: any) {
  return typeof value === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
}

function isReadableReferencePart(value: any) {
  if (value === undefined || value === null || value === "") return false;
  if (isUuid(value)) return false;
  if (typeof value === "object" && !Array.isArray(value)) return false;
  return formatValue(value) !== "-";
}

export function defaultOperationForm(kind: OperationKind, row?: any, endpoint = "") {
  if (kind === "preview-invoice" || kind === "generate-invoice") {
    const isPharmacyDispensation = endpoint === "/pharmacy/dispensations";
    return {
      patientId: row?.patientId ?? "",
      admissionId: row?.admissionId ?? "",
      from: "",
      to: "",
      sourceType: isPharmacyDispensation ? "DISPENSATION" : "",
      sourceId: isPharmacyDispensation ? row?.id ?? "" : "",
      draftId: `INV-DRAFT-${Date.now()}`,
      invoiceItems: [],
      collectNow: isPharmacyDispensation,
      paymentMethod: "CASH",
      paymentAmount: "",
      paymentReference: isPharmacyDispensation ? "Délivrance pharmacie" : "",
    };
  }
  if (kind === "pay-invoice") return { amount: row?.balanceDue ?? row?.balance_due ?? "", method: "CASH", reference: "" };
  if (kind === "discharge") return { summary: "" };
  if (kind === "complete-consultation") return { assessment: row?.assessment ?? "", plan: row?.plan ?? "", notes: row?.notes ?? "" };
  if (kind === "confirm-birth") return {
    pregnancyId: row?.id ?? "",
    motherPatientId: row?.patientId ?? row?.patient_id ?? "",
    deliveryAt: new Date().toISOString().slice(0, 16),
    firstName: "",
    lastName: "",
    gender: "UNKNOWN",
    birthWeightGrams: "",
    apgar1: "",
    apgar5: "",
    apgar10: "",
    cordPh: "",
    deliveryType: "VAGINAL",
  };
  if (kind === "send-to-surgery") {
    const start = new Date(Date.now() + 30 * 60_000);
    const end = new Date(start.getTime() + 90 * 60_000);
    return {
      operatingRoomId: "",
      surgeonId: "",
      anesthesiologistId: "",
      estimatedStartAt: start.toISOString().slice(0, 16),
      estimatedEndAt: end.toISOString().slice(0, 16),
      procedureName: "Césarienne / intervention obstétricale",
      procedureCode: "OBSTETRIC_SURGERY",
      priority: "URGENT",
      reason: "",
    };
  }
  if (kind === "surgery-status") return { status: nextSurgeryStatuses(row?.status)[0] ?? "INDUCTION" };
  if (kind === "validate-oms-step") return { step: row?.beforeInductionValidated ? row?.beforeIncisionValidated ? "before-exit" : "before-incision" : "before-induction" };
  if (kind === "stock-movement") return { stockItemId: row?.id ?? "", type: "RECEIPT", quantity: 1, reference: "" };
  if (kind === "change-status") return { status: nextStatuses(endpoint, row?.status)[0] ?? "", administeredAt: "", notes: "" };
  return {};
}

export function validateOperation(kind: OperationKind, form: Record<string, any>) {
  if ((kind === "preview-invoice" || kind === "generate-invoice") && !form.patientId) throw new Error("Sélectionnez le patient pour calculer la facture.");
  if ((kind === "preview-invoice" || kind === "generate-invoice") && form.from && form.to && new Date(form.to).getTime() < new Date(form.from).getTime()) throw new Error("La date de fin de facture doit être après la date de début.");
  if (kind === "generate-invoice" && form.collectNow && form.paymentAmount && (!Number.isFinite(Number(form.paymentAmount)) || Number(form.paymentAmount) <= 0)) throw new Error("Le montant encaissé doit être supérieur à 0.");
  if (kind === "pay-invoice" && (!Number.isFinite(Number(form.amount)) || Number(form.amount) <= 0)) throw new Error("Le montant encaissé doit être supérieur à 0.");
  if (kind === "stock-movement" && !form.stockItemId) throw new Error("Sélectionnez l’article de stock.");
  if (kind === "stock-movement" && (!Number.isFinite(Number(form.quantity)) || Number(form.quantity) <= 0)) throw new Error("La quantité du mouvement de stock doit être supérieure à 0.");
  if (kind === "discharge" && !String(form.summary ?? "").trim()) throw new Error("Le résumé de sortie est obligatoire.");
  if (kind === "complete-consultation" && (!String(form.assessment ?? "").trim() || !String(form.plan ?? "").trim())) throw new Error("Le diagnostic et le plan de traitement sont obligatoires.");
  if (kind === "confirm-birth" && (!form.pregnancyId || !form.motherPatientId)) throw new Error("Le dossier grossesse et la mère sont obligatoires.");
  if (kind === "confirm-birth" && !String(form.deliveryAt ?? "").trim()) throw new Error("La date et heure de naissance sont obligatoires.");
  if (kind === "confirm-birth" && form.apgar5 !== "" && (!Number.isFinite(Number(form.apgar5)) || Number(form.apgar5) < 0 || Number(form.apgar5) > 10)) throw new Error("L’Apgar à 5 minutes doit être entre 0 et 10.");
  if (kind === "send-to-surgery" && (!form.operatingRoomId || !form.surgeonId)) throw new Error("Sélectionnez la salle de bloc et le chirurgien.");
  if (kind === "send-to-surgery" && (!String(form.estimatedStartAt ?? "").trim() || !String(form.estimatedEndAt ?? "").trim())) throw new Error("Renseignez le créneau opératoire.");
  if (kind === "send-to-surgery" && new Date(form.estimatedEndAt).getTime() <= new Date(form.estimatedStartAt).getTime()) throw new Error("La fin prévue doit être après le début prévu.");
  if (kind === "send-to-surgery" && !String(form.procedureName ?? "").trim()) throw new Error("Renseignez la procédure opératoire.");
  if (kind === "surgery-status" && !String(form.status ?? "").trim()) throw new Error("Sélectionnez le statut de salle.");
  if (kind === "validate-oms-step" && !String(form.step ?? "").trim()) throw new Error("Sélectionnez l’étape OMS à valider.");
  if (kind === "change-status" && !String(form.status ?? "").trim()) throw new Error("Sélectionnez le nouveau statut.");
  if (kind === "change-status" && form.status === "ADMINISTERED" && "administeredAt" in form && !String(form.administeredAt ?? "").trim()) throw new Error("La date d’administration est obligatoire.");
}

function nextSurgeryStatuses(current?: string) {
  const transitions: Record<string, string[]> = {
    SCHEDULED: ["INDUCTION", "CANCELLED"],
    INDUCTION: ["INCISION", "CANCELLED"],
    INCISION: ["SUTURE", "CANCELLED"],
    SUTURE: ["RECOVERY_ROOM", "CANCELLED"],
    RECOVERY_ROOM: ["CLEANING", "COMPLETED"],
    CLEANING: ["COMPLETED"],
  };
  return transitions[String(current ?? "SCHEDULED").toUpperCase()] ?? ["INDUCTION", "INCISION", "SUTURE", "RECOVERY_ROOM", "CLEANING", "COMPLETED"];
}

export function nextStatuses(endpoint: string, current?: string) {
  const key = endpoint.replace(/^\//, "") === "surgery" ? "surgeries" : endpoint.replace(/^\//, "");
  const transitions: Record<string, Record<string, string[]>> = {
    "laboratory/orders": { ORDERED: ["COLLECTED", "IN_PROGRESS", "CANCELLED"], COLLECTED: ["IN_PROGRESS", "VALIDATED", "CANCELLED"], IN_PROGRESS: ["VALIDATED", "CANCELLED"] },
    "laboratory/samples": { PENDING: ["COLLECTED", "RECEIVED", "REJECTED"], COLLECTED: ["RECEIVED", "REJECTED"], RECEIVED: ["IN_ANALYSIS", "REJECTED"], IN_ANALYSIS: ["DONE", "REJECTED"] },
    "imaging/orders": { ORDERED: ["IN_PROGRESS", "VALIDATED", "CANCELLED"], IN_PROGRESS: ["VALIDATED", "CANCELLED"] },
    "nursing/tasks": { PENDING: ["DONE", "MISSED", "CANCELLED"] },
    "nursing/medications": { SCHEDULED: ["ADMINISTERED", "MISSED", "REFUSED", "CANCELLED"] },
    "nursing/handovers": { DRAFT: ["SIGNED", "ARCHIVED"], SIGNED: ["ARCHIVED"] },
    "icu/care-plans": { ACTIVE: ["COMPLETED", "CANCELLED"] },
    "icu/transfers": { REQUESTED: ["APPROVED", "CANCELLED", "DECEASED"], APPROVED: ["TRANSFERRED", "CANCELLED", "DECEASED"] },
    surgeries: { SCHEDULED: ["IN_PROGRESS", "COMPLETED", "CANCELLED"], IN_PROGRESS: ["COMPLETED", "CANCELLED"] },
    "surgery/requests": { REQUESTED: ["APPROVED", "SCHEDULED", "CANCELLED"], APPROVED: ["SCHEDULED", "CANCELLED"], SCHEDULED: ["COMPLETED", "CANCELLED"] },
    "surgery/recoveries": { RECOVERY: ["STABLE", "TRANSFERRED", "COMPLICATION"], STABLE: ["TRANSFERRED"], COMPLICATION: ["STABLE", "TRANSFERRED"] },
    "blood-bank/products": { AVAILABLE: ["RESERVED", "ISSUED", "EXPIRED", "DISCARDED"], RESERVED: ["AVAILABLE", "ISSUED", "DISCARDED"] },
    "blood-bank/collections": { COLLECTED: ["VALIDATED", "REJECTED"] },
    "blood-bank/requests": { REQUESTED: ["APPROVED", "CANCELLED"], APPROVED: ["RESERVED", "ISSUED", "CANCELLED"], RESERVED: ["ISSUED", "CANCELLED"] },
    "blood-bank/crossmatches": { PENDING: ["COMPATIBLE", "INCOMPATIBLE"] },
    "blood-bank/transfusions": { ORDERED: ["ADMINISTERED", "REACTION", "CANCELLED"], ADMINISTERED: ["REACTION"] },
    pregnancies: { ACTIVE: ["DELIVERED", "CANCELLED", "CLOSED"], DELIVERED: ["CLOSED"] },
    "insurance/claims": { SUBMITTED: ["APPROVED", "REJECTED", "PAID"], APPROVED: ["PAID", "REJECTED"] },
    "procurement/orders": { DRAFT: ["SENT", "CANCELLED"], SENT: ["RECEIVED", "CANCELLED"] },
    "hr/employees": { PROBATION: ["ACTIVE", "SUSPENDED", "TERMINATED", "RESIGNED"], ACTIVE: ["ON_LEAVE", "SUSPENDED", "RETIRED", "TERMINATED", "RESIGNED"], ON_LEAVE: ["ACTIVE", "SUSPENDED"], SUSPENDED: ["ACTIVE", "TERMINATED", "RESIGNED"] },
    "hr/contracts": { DRAFT: ["ACTIVE", "TERMINATED", "EXPIRED"], ACTIVE: ["RENEWED", "TERMINATED", "EXPIRED"], RENEWED: ["ACTIVE", "TERMINATED", "EXPIRED"] },
    "hr/leave-requests": { REQUESTED: ["SUPERVISOR_APPROVED", "REJECTED", "CANCELLED"], SUPERVISOR_APPROVED: ["HR_APPROVED", "REJECTED"], HR_APPROVED: ["ACTIVE", "CANCELLED"], ACTIVE: ["COMPLETED", "CANCELLED"] },
    "hr/payroll-periods": { OPEN: ["PROCESSING", "LOCKED", "CANCELLED"], PROCESSING: ["OPEN", "LOCKED", "CANCELLED"] },
    "hr/payroll-runs": { DRAFT: ["VALIDATED", "CANCELLED"], VALIDATED: ["LOCKED", "CANCELLED"] },
    "hr/payslips": { DRAFT: ["PUBLISHED", "CANCELLED"], PUBLISHED: ["PAID"] },
    "hr/documents": { PENDING: ["APPROVED", "REJECTED"], APPROVED: ["ARCHIVED"], REJECTED: ["PENDING"] },
  };
  return transitions[key]?.[String(current ?? "")] ?? [];
}
